# Generated by Django 3.2.4 on 2021-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_task_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('vf', 'Freshman'), ('pr', 'Sophomore')], default='vf', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='vacine_name',
            field=models.CharField(default='myname', max_length=200),
        ),
    ]
