# Generated by Django 3.2.4 on 2021-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210816_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMOR', 'Sophomore')], default='FRESHMAN', max_length=8),
        ),
    ]
