# Generated by Django 3.2.4 on 2021-08-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='expirydate',
        ),
    ]
